ALTER TABLE users ADD COLUMN IF NOT EXISTS fcm_token VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS apns_token VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_users_fcm_token ON users (fcm_token);
