ALTER TABLE bids ALTER COLUMN amount TYPE DECIMAL(12,2);
ALTER TABLE bids ALTER COLUMN amount SET NOT NULL;

ALTER TABLE auctions ALTER COLUMN winning_bid_amount TYPE DECIMAL(12,2) USING winning_bid_amount::DECIMAL(12,2);

-- Add missing auction columns
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS min_bid DECIMAL(12,2);
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS max_bid DECIMAL(12,2);
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS num_winners INT DEFAULT 1;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20);
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS payment_deadline TIMESTAMP;
